### ISSUE TITLE
module `traits` is private

### ISSUE THREAD

**Issue by mcseemk** [Alexhuszagh/rust-lexical#1]
Hello,

With lexical 1.5 the following code was fine:

> pub fn deserialize<'de, T, D>(deserializer: D) -> Result<T, D::Error>
>     where
>         T: lexical::traits::Aton,
>         D: Deserializer<'de> {
>     lexical::try_parse::<T, _>(String::deserialize(deserializer)?).map_err(de::Error::custom)
> }

Now it says: 

> error[E0603]: module `traits` is private

It looks like trait Aton has become FromBytes, but it still doesn't help as it cannot be used.

**Comment by Alexhuszagh** [comment]
@mcseemk Sorry for that inconvenience, I foolishly never considered that part of the public API, however, it was publicly exposed as an implementation detail. I've undergone massive changes under-the-hood recently to fix naming conventions and create a performant, correct float parser, and this work has been finished.

I've submitted the following patch, which should fix this issue by publicly exposing `FromBytes, FromBytesLossy, ToBytes`, as well as improving their documentation. If all is satisfactory, I'll push the release to crates.io.

**Comment by mcseemk** [comment]
Great, thanks! Please push it to crates.io then.

**Comment by Alexhuszagh** [comment]
Done as of v1.6.1.
