### ISSUE TITLE
[OTHER] Improve internal safety comments and architecture

### ISSUE THREAD

**Issue by Manishearth** [Alexhuszagh/rust-lexical#100]
I was reviewing the lexical-write-integer crate and I discovered a bunch of things that could be improved wrt safety.

The main issue was the one already filed as https://github.com/Alexhuszagh/rust-lexical/issues/95. That's actual UB, this issue is more about the safety comments and how the invariants are upheld. The `safe` mode doesn't disable this code that has actual UB, either.

Besides the issue that already exists, there are a whole bunch of functions (e.g. [`write_digits()`](https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-write-integer/src/algorithm.rs#L68)) that unsafely index from `table` are documented with "This is safe as long as the buffer is large enough to hold `T::MAX` digits in radix `N`.`",but they do not include the safety requirement on `table`.

Furthermore, some functions (also [`write_digits()`](https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-write-integer/src/algorithm.rs#L68)) take a `mut index: usize` argument that is used to directly index. These safety requirements are also not mentioned.

Besides safety comments, I found a couple areas where it was hard to review the unsafe code:

A bunch of code relies on the radix being from amongst a valid set (e.g. [`get_table()`](https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-write-integer/src/table_binary.rs#L29)). May benefit from being an enum; it's hard to tell if this invariant is being upheld.

Other code which is calling the `write_*()` functions (e.g. [`unsigned()`](https://github.com/Alexhuszagh/rust-lexical/blob/main/lexical-write-integer/src/api.rs#L21)) declare they are safe as long as the buffer can hold `FORMATTED_SIZE` elements, but that invariant is not really clear from the functions used, it's kinda hidden away.

Might be cool to have a `ValidBuffer<FORMAT>` wrapper that allows calling these write functions in an encapsulated way.

Anyway, hope this helps. I don't have time to devote to doing this work myself but I figured I'd share my notes in case someone else does.

**Comment by Alexhuszagh** [comment]
I'll be looking comprehensively over this later today.

**Comment by Alexhuszagh** [comment]
I've made some major progress on this on the [safety](https://github.com/Alexhuszagh/rust-lexical/tree/safety) branch, benchmarking every significant change I've made to avoid any regressions while slowly removing unsafety. I had high-level "unchecked" functions which I removed to allow more localized safety invariants.

**Comment by Alexhuszagh** [comment]
I'll be also adding in documentation at the top of each module that uses unsafe code what the general purpose guarantees are and then better `# SAFETY` invariant documentation internally. There's a few cases where I wasn't able to remove unsafety (this is performance related, often with a 20%+ hit in performance) despite relative easy of proving that the code was safe so I'm also commenting on why the unsafety remains.

**Comment by Alexhuszagh** [comment]
This has now been closed: ~90% of all unsafety has been removed and all that remains is trivial to verify with major documentation on the vulnerable parts. The crate documentation also now clearly describes the possible sources of unsoundness, why the code is sound, and any other requirements.

Once #135 I'll remove this and publish this to crates.io.

**Comment by Manishearth** [comment]
@Alexhuszagh looking briefly through the remaining unsafe, I still feel like a lot of it can still be reduced. E.g. there are safe parser patterns that avoid peek/unchecked semantics. There ought to be ways to encapsulate the unsafety better.

1000+ unsafe blocks, even if documented, is still a lot to review, so I don't suspect anyone will perform a new audit any time soon for this.

(There are basically two ways you can have 1000 unsafe blocks: either they're all very different, in which case that's a huge task to review, or there are a lot of similarities, in which case there can probably be some safe abstractions built)

**Comment by Alexhuszagh** [comment]
> (There are basically two ways you can have 1000 unsafe blocks: either they're all very different, in which case that's a huge task to review, or there are a lot of similarities, in which case there can probably be some safe abstractions built)

I tried this a few ways, but one of them was using `read_if` and encapsulating everything there, which unfortunately didn't have close to the performance I was looking for.

```rust
    /// Peek the next value and consume it if the read value matches the
    /// expected one.
    #[inline(always)]
    fn read_if<Pred: FnOnce(&u8) -> bool>(&mut self, pred: Pred) -> Option<Self::Item> {
        if let Some(peeked) = self.peek() {
            if pred(peeked) {
                // SAFETY: the slice cannot be empty because we peeked a value.
                unsafe { self.step_unchecked() };
                Some(peeked)
            } else {
                None
            }
        } else {
            None
        }
    }
```

However, a lot of the remaining unsafety would be in the implementation of the stack vector and the iterator API:
https://github.com/Alexhuszagh/rust-lexical/blob/aeab32205c18c4569402f83817eeb9fb983ee64b/lexical-util/src/iterator.rs#L30

https://github.com/Alexhuszagh/rust-lexical/blob/aeab32205c18c4569402f83817eeb9fb983ee64b/lexical-parse-float/src/bigint.rs

Both of which are fully encapsulated.

**Comment by Alexhuszagh** [comment]
A large percentage of it remaining was the `Options` API, which originally had only 2 functions in it that were actually unsafe (`set_nan_string`, `set_inf_string`), but the rest were reserved as unsafe since any use without validating our format specifications with `is_valid` was breaking our guarantees. However, none of those are unsafe and after removing them, we're at 417 total unsafe expressions in `lexical-core`, of which the majority are in 1 or 2 encapsulated classes.

**Comment by Manishearth** [comment]
Thanks. Yeah I find it incredibly unlikely that this amount of unsafe is necessary for performance, a lot of these encapsulations can be zero cost. 315 is still a lot but more manageable.

**Comment by Alexhuszagh** [comment]
We're down to less than 250 unsafe expressions and almost all of it is within 2 abstractions: `Iter` and `Bigint`. Since these abstractions are fully encapsulated except for a few invocations where the guarantees are clearly written, there is practically no non-encapsulated unsafety left, so I feel comfortable reclosing this.

We have <60 expressions of unsafe code outside of those 2 abstractions. A lot of the remaining unsafety is code like this:

```rust
    // Compute xi and zi.
    // SAFETY: safe, since value must be finite and therefore in the correct range.
    // `-324 <= exponent <= 308`, so `x * log10(2) - log10(4 / 3)` must be in
    // `-98 <= x <= 93`, so the final value must be in [-93, 98] (for f64). We have
    // precomputed powers for [-292, 326] for f64 (same logic applies for f32) so
    // this is **ALWAYS** safe.
    let pow5 = unsafe { F::dragonbox_power(-minus_k) };
```

Overall, this introduces 8 unsafe expressions, which out of almost the entire remainder is in the integer writer, which is a well-known algorithm and has a major performance hit if it uses checked indexing.

I think this is acceptable.
