### ISSUE TITLE
[BUG] Unsoundness: `try_parse_{4,8}digits` appear to advance iterators out of bounds

### ISSUE THREAD

**Issue by Ralith** [Alexhuszagh/rust-lexical#101]
`BytesIter::read` is documented as advancing the iterator's state:
https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-util/src/iterator.rs#L123-L125

However, the `try_parse_4digits` and `try_parse_8digits` methods advance the iterator's state manually after reading, without any other apparent length checks:

https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-parse-integer/src/algorithm.rs#L220-L223

https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-parse-integer/src/algorithm.rs#L293-L295

This is unsound according to the docs of `step_by_unchecked`:
https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-util/src/iterator.rs#L131-L133

Skimming around for actual implementations, it appears that `read` may not actually advance the state as advertised, which could explain how this has gone unnoticed so far. Note the absence of any mutation of `self.index`, contrary to the doc comment:

https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-util/src/noskip.rs#L102-L118

**Comment by Alexhuszagh** [comment]
This was resolved as of commit #103. If I'm wrong about this, please re-open this or create another issue. All checks now should be done without any debug asserts, using:

```rust
    /// Try to read a the next four bytes as a u32.
    /// This advances the internal state of the iterator.
    #[inline(always)]
    pub fn read_u32(&self) -> Option<u32> {
        if Self::IS_CONTIGUOUS && self.as_slice().len() >= mem::size_of::<u32>() {
            // SAFETY: safe since we've guaranteed the buffer is greater than
            // the number of elements read. u32 is valid for all bit patterns
            unsafe { Some(self.read_unchecked()) }
        } else {
            None
        }
    }

    /// Try to read the next eight bytes as a u64
    /// This advances the internal state of the iterator.
    #[inline(always)]
    pub fn read_u64(&self) -> Option<u64> {
        if Self::IS_CONTIGUOUS && self.as_slice().len() >= mem::size_of::<u64>() {
            // SAFETY: safe since we've guaranteed the buffer is greater than
            // the number of elements read. u64 is valid for all bit patterns
            unsafe { Some(self.read_unchecked()) }
        } else {
            None
        }
    }
```
