### ISSUE TITLE
Return to Active Development

### ISSUE THREAD

**Issue by Alexhuszagh** [Alexhuszagh/rust-lexical#109]
Hi All,

Sorry for the long time away: I will be working on this project again and am actively running through the backlog. I will close this as I get closer to completing this.

Alex

**Comment by samuelcolvin** [comment]
This is great news, `lexical-parse-float` is used by [jiter](https://github.com/pydantic/jiter), which (as part of pydantic and as a standalone package) is the most downloaded JSON parser for Python.
