### ISSUE TITLE
lexical::Error should impl std::error::Error

### ISSUE THREAD

**Issue by danburkert** [Alexhuszagh/rust-lexical#11]
This is useful when exposing a `lexical::Error` through a wrapping-error's `source` or `cause` method.

**Comment by Alexhuszagh** [comment]
Added in b19492351a39b4b46d6d5b1439625ce8f3e583bd. Should be pushed to the newest version soon.

**Comment by NotSqrt** [comment]
Hello,

It seems the `impl StdError for Error` was dropped in e644602c681011 when `src/error.rs` was dropped, and not moved into `lexical-core/src/util/error.rs`.

Was there a specific reason to drop it ?
Thanks !

**Comment by myrrlyn** [comment]
It was likely dropped because `lexical-core` is a `#![no_std]` library. It has been restored when `feature = "std"` is present. I apologize for the delay.

**Comment by Alexhuszagh** [comment]
@myrrlyn Thanks for merging this. @NotSqrt It was originally removed since most of the methods I was depending on were deprecated (`description`), and downcasting wasn't off relevance to this library, and my shortsightedness I didn't think downstream. Thanks for fixing this.
