### ISSUE TITLE
[OTHER] Outdated `itoa` dependency in benchmarks

### ISSUE THREAD

**Issue by zheland** [Alexhuszagh/rust-lexical#144]
## Description

Benchmarks code uses outdated versions for some libraries with which the comparison is made.

For example, the version of `itoa` is `0.4`, whereas the latest version is `1.0.11`. Major `itoa` `1.0.0` was released about 3 years ago and has become more competitive in performance with `lexical`.

## Examples
Update example for `itoa`:
```diff
diff --git a/lexical-benchmark/input.rs b/lexical-benchmark/input.rs
index 3bad58d..abf6f33 100644
--- a/lexical-benchmark/input.rs
+++ b/lexical-benchmark/input.rs
@@ -449,16 +449,11 @@ macro_rules! ryu_generator {
 
 macro_rules! itoa_generator {
     ($group:ident, $name:expr, $iter:expr) => {{
-        use lexical_util::constants::BUFFER_SIZE;
-        let mut buffer = vec![b'0'; BUFFER_SIZE];
+        let mut buffer = itoa::Buffer::new();
         $group.bench_function($name, |bench| {
             bench.iter(|| {
                 $iter.for_each(|&x| {
-                    itoa::write(&mut buffer, x).unwrap();
-                    black_box(&buffer);
-                    unsafe {
-                        buffer.set_len(0);
-                    }
+                    black_box(buffer.format(x));
                 })
             })
         });
diff --git a/lexical-benchmark/write-integer/Cargo.toml b/lexical-benchmark/write-integer/Cargo.toml
index a0555bc..fc03dc6 100644
--- a/lexical-benchmark/write-integer/Cargo.toml
+++ b/lexical-benchmark/write-integer/Cargo.toml
@@ -17,7 +17,7 @@ features = []
 
 [dev-dependencies]
 criterion = { version = "0.5.0", features = ["html_reports"] }
-itoa = { version = "0.4", features = ["i128"] }
+itoa = "1.0.11"
 fastrand = "2.1.0"
 lazy_static = "1"
 serde = { version = "1.0", features = ["derive"] }
```

## Benchmarks
Benchmark results for `write-integer`, `random:simple` , changes making `itoa` more competitive.
Local benchmark results part:
| type | lexical | itoa (old) | itoa (new) |
|-|-|-|-|
| u8 | 865.20 ns | 2.4429 µs | 820.91 ns |
| u16 | 2.4149 µs | 3.0292 µs | 1.4237 µs |
| u32 | 1.5374 µs | 3.0876 µs | 1.4502 µs |
| u64 | 1.7303 µs | 3.5951 µs | 1.5353 µs |

It might be a good thing to update the versions of all libraries with which the comparison is made.

## Notes

* Updated at Sep 17 08:07 GMT: replaced `+itoa = { version = "1.0.11" }` with `+itoa = "1.0.11"`

**Comment by Alexhuszagh** [comment]
Sounds good, this will also need to be reflected in https://github.com/Alexhuszagh/lexical-benchmarks.

**Comment by Alexhuszagh** [comment]
I've got scripts that are almost complete in [lexical-benchmarks](https://github.com/Alexhuszagh/lexical-benchmarks) that will autoplot the comparison so we can keep up-to-date values and correct these benchmarks.

![random_uniform - write int - fmt,itoa,lexical](https://github.com/user-attachments/assets/0e2efd44-a823-463f-91cb-a360eb890ada)
![random_simple_signed - write int - fmt,itoa,lexical](https://github.com/user-attachments/assets/a40dafe3-a7b3-4d0f-8fdd-a793601716b2)
![json_random - write int - fmt,itoa,lexical](https://github.com/user-attachments/assets/a26031b3-c6b7-40aa-9229-75b16bfa63cc)

Which there's many other plots. I think this is a much better comparison: `itoa` wins in most of these which is great (it's a smaller library and if it works well all the better).
