### ISSUE TITLE
[BUG] Unit tests failures

### ISSUE THREAD

**Issue by alexanderkjall** [Alexhuszagh/rust-lexical#169]
## Description

`cargo test --no-default-features --features radix` fails two unit tests: `i128_proptest_radix and `u128_proptest_radix` on my amd64 machine.

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version: `rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1)`
- lexical version: 1.0.2
- lexical compilation features used: ` --no-default-features --features radix`

## Test case

See above, it's the existing unit tests. 

## Additional Context

`cargo test --no-default-features --features power-of-two` also have some failing tests: `binary_test` and `u128toa_proptest`

**Comment by Alexhuszagh** [comment]
Attaching the output of the failures:

[power-of-two.txt](https://github.com/user-attachments/files/17385064/power-of-two.txt)
[radix.txt](https://github.com/user-attachments/files/17385065/radix.txt)

**Comment by Alexhuszagh** [comment]
I've diagnosed the cause of the issue, will have a patch incoming shortly.

**Comment by alexanderkjall** [comment]
Thanks for being so responsive :)

**Comment by Alexhuszagh** [comment]
Sorry I haven't forgotten about this and am working on it. Other open source work and work work has gotten in the way. This is still my highest priority for this crate at the moment.

**Comment by Alexhuszagh** [comment]
Sorry for the massive delay on this, I've implemented a large number of patches and optimizations and completed this. I will be drafting up a release shortly.

**Comment by Alexhuszagh** [comment]
Published as of version 1.0.3.

**Comment by alexanderkjall** [comment]
thanks a lot :)
