### ISSUE TITLE
Parsing of '.'

### ISSUE THREAD

**Issue by RazrFalcon** [Alexhuszagh/rust-lexical#2]
Rust will parse `.` as `Err(ParseFloatError { kind: Invalid })`, while `rust-lexical` will parse it as `0.0`. Not sure which one is the "correct" one.

**Comment by Alexhuszagh** [comment]
This is unintended behavior, and should be fixed. Great catch. Both "0." and ".0" are valid, however, "." is not.

**Comment by Alexhuszagh** [comment]
Fixed as of f0707c0. "0." and ".0" are both still considered valid floats. Please note you must use the "try_atof64_slice" in order to get the desired behavior.
