### ISSUE TITLE
Consider replacing stackvector with arrayvec

### ISSUE THREAD

**Issue by matklad** [Alexhuszagh/rust-lexical#22]
Hey, that's me again bugging you about arrayvec :) 

It looks like the two crates are pretty close in the end, and I wonder if it makes sense for `rust-lexical` to switch to the latter? arrayvec has seen much more usage in the ecosystem, and, because `unsafe` code is involved, it seems like it makes sense to minimize duplication? 

The there's the problem that `ArrayVec` lacks `insert_many` method, but I wonder if adding a
[splice](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.splice) method would help with that?

(The reason why I am asking about this is that I've noticied that rust-analyzer transitively, via `nom`, depends on `stackvector`, while it already has `arrayvec` among the deps`).

**Comment by Alexhuszagh** [comment]
This should be implemented as of 5781ea617a98c76355d7dcea42a450f0cbe1e6ee, waiting for various tests to run and to benchmark performance.

**Comment by Alexhuszagh** [comment]
Fixed for both lexical-core versions [0.6.0](https://crates.io/crates/lexical-core/0.6.0) and [0.4.5](https://crates.io/crates/lexical-core/0.4.5). Since nom currently uses the 0.4 version of lexical-core, arrayvec will be used by default. Thanks for finding this.
