### ISSUE TITLE
Better documentation for *toa_slice

### ISSUE THREAD

**Issue by RazrFalcon** [Alexhuszagh/rust-lexical#3]
https://docs.rs/lexical-core/0.1.3/lexical_core/ftoa/fn.f64toa_slice.html

1. How big the `bytes` input should be?
1. What exactly does this function returns?

**Comment by Alexhuszagh** [comment]
@RazrFalcon Great catch, sorry, the low-level API has extremely poor documentation.

I'm going to expose the variable [BUFFER_SIZE](https://github.com/Alexhuszagh/rust-lexical/blob/cc8778384e6d77031b45aef2cb9cb831670573d6/lexical-core/src/util/config.rs#L49), which is the maximum number of bytes any formatter may use.

The function returns a slice to the actually used parts of the buffer, for example, if you provide a buffer of 256-bytes, and it only uses the first 2, it returns a slice to the same buffer, but with a length of 2.

The range functions, the C FFI ones, return a pointer to the last used character + 1 (like in C++ ranges, so `for (p = first; p < last; p++) { ... }` works idiomatically.

**Comment by Alexhuszagh** [comment]
@RazrFalcon This should be remediated in the latest [commit](c0fb1c91c3c6cee1552391c418300f90b6a49a25). The READMEs have been significantly revamped, the variables for the maximum number of bytes the serializers will write have been documented and exported to the crate root, and the functions have accurate, detailed documentation explaining their functionality, arguments, and return values.

I'm going to add some more benchmarks before I push this to crates.io, but let me know if you have any concerns. You can build the documentation and view it locally using `cargo doc` with the master branch.

**Comment by RazrFalcon** [comment]
Yes, it's much nicer now.

As for panic functions, you should add a panic paragraph. [Example.](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve)

**Comment by Alexhuszagh** [comment]
The panic conditions should be added now, for both high and low-level code. Let me know if there are any lingering issues with the documentation. I had to trim the source tree, (just removing built binaries that accidentally got into the tree), so you may have to force a pull or rebase.

**Comment by RazrFalcon** [comment]
Everything is ok now.

**Comment by Alexhuszagh** [comment]
Fixed as of lexical-core 0.2.
