### ISSUE TITLE
Implement std::error::Error trait for lexical::Error

### ISSUE THREAD

**Issue by kangalioo** [Alexhuszagh/rust-lexical#39]
## Problem
rust-lexical does not implement the `std::error::Error` trait for `lexical::Error`.

That makes error handling harder, in my case the integration with `anyhow`. `anyhow` is a very helpful error handling helper library, but it requires the errors to implement the `std::error::Error` trait. `lexical` does not do that, which is why I'm gonna have to write boilerplate code to make it work correctly

## Solution
Implement the `std::error::Error` trait for `lexical::Error`.

## Prerequisites
None, as far as I can tell. I'm a Rust beginner, but I think an implementation of `std::error::Error` should require nothing beyond just a couple lines of code.

## Alternatives
Alternative: not do anything.
- Advantage: less work
- Disadvantage: crate is harder to work with and integrate with other crates

**Comment by kangalioo** [comment]
I saw #11, and it seems like a `std::error::Error` was once added but since removed (by accident?). If there were valid reasons to remove the implementations I would love to hear them :) And if it actually was an accident, it would be cool if the `std::error::Error` impl could be added back soon.

**Comment by myrrlyn** [comment]
This will be present in the next release.
