### ISSUE TITLE
[FEATURE] The Schubfach algorithm

### ISSUE THREAD

**Issue by plokhotnyuk** [Alexhuszagh/rust-lexical#42]
## Problem
While the Ryu algorithm shows fine average throughput for arbitrary numbers.

But it does a lot of rounding iterations for numbers with a small mantissa (in serialized representation) and have no version for bases except decimal.

## Solution
Use the Schubfach algorithm to avoid rounding loops. 

It will minimize tail latency or increase throughput if input has lot of numbers a with small mantissa.

Also, the Schubfach algorithm can be implemented for other bases except 3, 12, 24, 48, etc.

## Additional Context
["The Schubfach way to render doubles"](https://drive.google.com/file/d/1luHhyQF9zKlM8yJ1nebU0OgVYhfC6CBN/view) by Raffaello Giulietti 
[Java variant for decimal representation from the author of the algorithm](https://github.com/c4f7fcce9cb06515/Schubfach/tree/3c92d3c9b1fead540616c918cdfef432bca53dfa/todec)
[Scala variant for decimal representation from the jsoniter-scala library](https://github.com/plokhotnyuk/jsoniter-scala/blob/daa4e095236ae5b2bd04542810cc4f01d0857f57/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1759-L2097)

**Comment by Alexhuszagh** [comment]
Implemented as of [lexical v6.0.0](https://crates.io/crates/lexical/6.0.0) and [lexical-core v0.8.0](https://crates.io/crates/lexical-core/0.8.0), which uses the faster Dragonbox algorithm, an extension of the Schubfach principle.
