### ISSUE TITLE
The repository is HUGE (500 MB), consider cleaning it up (remove lexical-core/target)

### ISSUE THREAD

**Issue by jonenst** [Alexhuszagh/rust-lexical#5]
The repository is almost 500 megabytes due to including the lexical-core/target

git allows you to cleanup this using things like filter-branch, etc.

It will change the commit ids of the commits after the one where you accidentally added the lexical-core/target folder though, so contributors with old histories will get conflicts, but it's still largely worth it IMHO.

**Comment by jonenst** [comment]
I ran
$ git filter-branch --tree-filter 'rm -rf lexical-core/target' --prune-empty HEAD
$ git gc --aggressive

after cloning
$ git clone jon@localhost:/tmp/sdf/rust-lexical  # cloning from the filesystem doesn't prune

the repo is down to 14 MB

**Comment by Alexhuszagh** [comment]
I believe that's in a prior commit where there was a bug in my .gitignore, thanks for catching this. The repository is rather large, and should not be so. My fault. Let me clean this up.

**Comment by Alexhuszagh** [comment]
Done as of d78c0b1.
