### ISSUE TITLE
[BUG] Compilation Fails on Latest Nightly

### ISSUE THREAD

**Issue by HTG-YT** [Alexhuszagh/rust-lexical#55]
## Description

When building the crate with the latest nightly, the compilation fails with 27 errors.

## Prerequisites

- Rust version : `rustc 1.51.0-nightly (d4e3570db 2021-02-01)`
- lexical version: 0.7.4

All of them are E0308 and E0277

**Comment by HTG-YT** [comment]
The compilation works on the nightly build on 2021-01-31.

**Comment by HTG-YT** [comment]
@Alexhuszagh would you like to fix it?

**Comment by thomaseizinger** [comment]
Here is an example build: https://github.com/testcontainers/testcontainers-rs/runs/1811323780?check_suite_focus=true

**Comment by HTG-YT** [comment]
It looks like `<integer>::BITS` has been stabilized in the standard library, therefore that Limb::BITS resolved into a u32 instead of usize.

**Comment by astraw** [comment]
Looks like rust nightly will [revert the change](https://github.com/rust-lang/rust/issues/76904#issuecomment-772836505) until lexical-core can implement a suitable fix.

**Comment by rainliu** [comment]
Got the same error in https://github.com/webrtc-rs/ice/runs/1836585080
