### ISSUE TITLE
Remove needless uses of `unsafe`

### ISSUE THREAD

**Issue by llogiq** [Alexhuszagh/rust-lexical#6]
There's a lot of `unsafe` code in lexical_core. A lot of it appears to be dealing with pointers, where you have a `start` and `end` pointer pair, which could as well be a slice and be completely safe with acceptable performance cost.

**Comment by Alexhuszagh** [comment]
The relevant code for the work-in-progress to minimize the use of unsafe features is now on the [safe branch](https://github.com/Alexhuszagh/rust-lexical/tree/safe).

**Comment by Alexhuszagh** [comment]
Should have been fixed as of the 2.0 release (and the 0.3 release of lexical-core).
