### ISSUE TITLE
[OTHER] Yank versions incompatbile with Rust 1.53.0

### ISSUE THREAD

**Issue by legoktm** [Alexhuszagh/rust-lexical#65]
## Prerequisites

If applicable to the issue, here are a few things you should provide to help me understand the issue:

- Rust version: `rustc -V` 1.53.0
- lexical version: 0.7.4
- lexical compilation features used:

## Description
Please include a clear and concise description of the issue.

Refs https://github.com/Alexhuszagh/rust-lexical/issues/55, https://github.com/rust-lang/rust/issues/85667

It would be nice if the versions that are incompatible with Rust 1.53.0 could be yanked. While yanking doesn't force people to update to the fixed versions, it does help as tools like `cargo-audit` will now warn that you're using a yanked version and should upgrade.

## Additional Context
Add any other context or screenshots about the issue here.

At https://github.com/rust-lang/rust/issues/85667#issuecomment-847883676 @Mark-Simulacrum said "I think yanking is likely not the right step to take at this time." - I wonder if they still think that now that 1.53.0 is stable.

**Comment by Mark-Simulacrum** [comment]
Yanking isn't generally a good idea for cases like this; it unnecessarily causes churn for users who haven't upgraded to Rust 1.53 and isn't broadly common in the ecosystem today to my knowledge.

**Comment by Alexhuszagh** [comment]
Every single branch, even unmaintained ones, have been made compatible with Rust 1.53.0, so as long as any users aren't fixed on a specific version, lexical should not have issues.

Merely running `cargo update` should always update you to a version compatible, and since `cargo yank` does not prevent existing crates locked to a specific version from using an old, incompatible version, I don't believe yanking is the proper solution.

**Comment by Alexhuszagh** [comment]
I'm open to re-opening this or merging changes if the Rust core team decides it's a good idea, in the meantime, I've updated every branch (v0.4 to v0.7) to ensure it does not cause compatibility issues with Rust 1.53, so these issues should hopefully be fixed as long as users aren't locked to a version.

**Comment by xfix** [comment]
This would be appreciated for `cargo update -Z minimal-versions` builds (see https://github.com/rust-lang/cargo/issues/5657). Currently `minimal-versions` picks those old versions and to avoid that they could be yanked.
