### ISSUE TITLE
[BUG] Tests fail to compile because quickcheck is missing from Cargo.toml in the crates.io tarball.

### ISSUE THREAD

**Issue by emixa-d** [Alexhuszagh/rust-lexical#88]
## Description

When compiling `rust-lexical-util`, it fails with the following error:

```
Compiling tests/mul_tests.rs to .guix-tests/mul_tests
error[E0432]: unresolved import `quickcheck`
 --> tests/mul_tests.rs:2:5
  |
2 | use quickcheck::quickcheck;
  |     ^^^^^^^^^^ use of undeclared crate or module `quickcheck`

error: cannot determine resolution for the macro `quickcheck`
 --> tests/mul_tests.rs:4:1
  |
4 | quickcheck! {
  | ^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports
```

If I understand correctly, the issue is that the dependency `quickcheck` is not mentioned in the `Cargo.toml`, so the build system doesn't know to add --extern=quickcheck=... (abbreviated):

```
# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO
# [...]
[package]
edition = "2018"
name = "lexical-util"
[...]
[dependencies.static_assertions]
version = "1"
[dev-dependencies.proptest]
version = "0.10.1"

[features]
[...]
```

**Comment by emixa-d** [comment]
Oops, I didn't mean to assign anyone.

**Comment by emixa-d** [comment]
Working-around it by replacing the `Cargo.toml` by `Cargo.toml.orig`.

**Comment by Alexhuszagh** [comment]
> Working-around it by replacing the `Cargo.toml` by `Cargo.toml.orig`.

Assigning me is fine, thanks.

**Comment by emixa-d** [comment]
Likewise for lexical-parse-float

**Comment by Alexhuszagh** [comment]
This has been patched and will be released later today.
