### ISSUE TITLE
[BUG] Integer overflow checking logic is incorrect

### ISSUE THREAD

**Issue by ivan-shrimp** [Alexhuszagh/rust-lexical#91]
## Description

The current overflow checking logic for integers cannot check for all numeric overflow, as shown in this failing test case:

```rust
// 356 cannot be stored in a `u8`, so this should return an error
lexical::parse::<u8, _>("357").unwrap_err();
```

Specifically, the problem seems to be this claim in the [algorithm description](https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-parse-integer/docs/Algorithm.md):

> We have numerical overflow on two cases: we parsed more digits than we theoretically could, or we parsed the same number as the maximum, but the number wrapped. Since the number wrapping will always produce a smaller value than the minimum value for that number of digits, this is a simple comparison.

In the test case above, `357` would wrap to `101`, which is not smaller than the minimum value (`100`) for the maximum number of digits (3 digits for `u8`).

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version: `rustc 1.68.0-nightly (ad8ae0504 2022-12-29)`
- lexical version: 6.1.1
- lexical compilation features used: default

## Test case

```rust
fn main() {
    lexical::parse::<u8, _>("354").unwrap_err(); // pass
    lexical::parse::<u8, _>("355").unwrap_err(); // pass
    lexical::parse::<u8, _>("356").unwrap_err(); // fail, returns Ok(100)
    lexical::parse::<u8, _>("357").unwrap_err(); // fail, returns Ok(101)
    lexical::parse::<u8, _>("358").unwrap_err(); // fail, returns Ok(102)
                                                 // ...
    lexical::parse::<u8, _>("510").unwrap_err(); // fail, returns Ok(254)
    lexical::parse::<u8, _>("511").unwrap_err(); // fail, returns Ok(255)
    lexical::parse::<u8, _>("512").unwrap_err(); // pass
    lexical::parse::<u8, _>("513").unwrap_err(); // pass
    lexical::parse::<u8, _>("514").unwrap_err(); // pass

    lexical::parse::<u8, _>("612").unwrap_err(); // fail, returns Ok(100)
    lexical::parse::<u8, _>("999").unwrap_err(); // fail, returns Ok(231)
    lexical::parse::<u8, _>("1000").unwrap_err(); // pass

    let n = u32::MAX as u64 + 1_000_000_000;
    lexical::parse::<u32, _>((n - 1).to_string()).unwrap_err(); // pass
    lexical::parse::<u32, _>(n.to_string()).unwrap_err(); // fail
    lexical::parse::<u32, _>((n + 1).to_string()).unwrap_err(); // fail

    lexical::parse::<i8, _>("357").unwrap_err(); // fail, returns Ok(101)
}
```

Using lexical-parse-integer 0.8.6 directly:

```rust
fn main() {
    use lexical_parse_integer::FromLexical;

    u8::from_lexical(b"357").unwrap_err(); // fail, returns Ok(101)
}
```

## Additional context

The incorrect logic seems to be implemented here:
https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-parse-integer/src/shared.rs#L159-L176

**Comment by Alexhuszagh** [comment]
I should have a solution for this soon.
