### ISSUE TITLE
[BUG] -0.0 printed as "0.0"

### ISSUE THREAD

**Issue by mwkmwkmwk** [Alexhuszagh/rust-lexical#94]
## Description

The `write_float` functionality does not print the sign of negative 0.

## Prerequisites

- Rust version: `rustc 1.70.0-nightly (478cbb42b 2023-03-28)`
- lexical version: 6.1.1
- lexical compilation features used: [defaults]

## Test case

Example test case:

```
fn main() {
    let f: f64 = -0.0;
    let s = lexical::to_string(f);
    assert_eq!(s, "-0.0");
}
```

**Comment by ArchLeaders** [comment]
Any progress toward fixing this bug?
