### ISSUE TITLE
[BUG] Safety comments for MaybeUninit::assume_init calls are wrong, calls are UB

### ISSUE THREAD

**Issue by saethlin** [Alexhuszagh/rust-lexical#95]
This code executes UB: https://github.com/Alexhuszagh/rust-lexical/blob/09c686b075096d48155cfb32265068f962afc56c/lexical-write-float/src/radix.rs#L70-L72

The docs for `MaybeUninit::uninit` do not have an exception for this use case. This code is UB, because the `MaybeUninit` is not initialized.

The safety comment is also _technically_ wrong; the value is read by the assignment and return from `MaybeUninit::assume_init`.

This problem is reliably reported by running `cargo +nightly miri test --all-features`.

---

The existing `MaybeUninit` APIs are not exactly elegant, but I think they can be slotted in pretty neatly with the existing abstractions you have here. I can take a shot at fixing this in the coming days/weeks.

**Comment by workingjubilee** [comment]
> I was (incorrectly) under the assumption ptr.write() was defined behavior

What do you mean by "`ptr.write()` was defined behavior"?
Did you mean you assumed that `uninit.assume_init()` and `ptr.write()` were allowed to be ordering-independent?

**Comment by Alexhuszagh** [comment]
> > I was (incorrectly) under the assumption ptr.write() was defined behavior
> 
> What do you mean by "`ptr.write()` was defined behavior"? Did you mean you assumed that `uninit.assume_init()` and `ptr.write()` were allowed to be ordering-independent?

Correct, that's my mistake. I'm doing a comprehensive analysis of all unsafe behavior within lexical and will be adding much more comprehensive testing and ensure safety guarantees are more stringent, removing more unsafe behavior, and ensuring that code quality is up to scratch for the next major release.

I apologize for this and my late response.

**Comment by workingjubilee** [comment]
It is fine if you **write first**.

Mostly, we are currently debating how we can improve our `MaybeUninit::assume_init` docs to make this clearer.

**Comment by Alexhuszagh** [comment]
I greatly appreciate that, it makes sense on a closer inspection but I made some major mistakes here in my initial assessment. That would be a huge help I'm sure to many additional developers.

I've done some benchmarks and found I can zero-initialize with comparable performance so I'll be removing the use of `MaybeUninit` in these locations.

**Comment by Alexhuszagh** [comment]
I'll be rushing out a major release by the end of the week, and I'll be slowly ensuring more safety invariants are upheld and yanking previous versions as required. 

Also, on another note: I highly appreciate how helpful both of you have been in explaining this to me. I've added Miri workflows to our pipelines so any time unsafe code is modified we can ensure safety with this and fuzzing. I know this has been a major issue and I'm glad to have had some help in this process.
