### ISSUE TITLE
[BUG] `no_integer_leading_zeros(true)` incorrectly parses input

### ISSUE THREAD

**Issue by indietyp** [Alexhuszagh/rust-lexical#98]
## Description

If enabling `no_integer_leading_zeros` (such as with the `JSON` format), if the input contains a leading `0`, the input correctly parses, even if it shouldn't.

## Minimum Reproducible Example

(uses the nightly cargo-script feature)

Here are a few things you should provide to help me understand the issue:

- Rust version: `rustc 1.72.0-nightly (6162f6f12 2023-07-01)`

```rust
//! ```cargo
//! [dependencies]
//! lexical = { version = "6.1.1", features = ['power-of-two', 'format'] }
//! ```
use lexical;
use lexical::ParseIntegerOptions;
use lexical::NumberFormatBuilder;

const DECIMAL_FORMAT: u128 = NumberFormatBuilder::new()
    .required_digits(true)
    .no_positive_mantissa_sign(false)
    .no_special(true)
    .no_integer_leading_zeros(true)
    .no_float_leading_zeros(false)
    .build();

fn main() {
    let a =
        lexical::parse_with_options::<i64, _, DECIMAL_FORMAT>(b"1.1.0", &ParseIntegerOptions::new());

    let b =
        lexical::parse_with_options::<i64, _, DECIMAL_FORMAT>(b"0.1.0", &ParseIntegerOptions::new());

    println!("A: {a:?}");
    println!("B: {b:?}")
}
```

Run with `cargo +nightly -Zscript lexical.rs`

As you can see, if `no_integer_leading_zeros` is set, `b` successfully parses to `Ok(0)`, even though it shouldn't.

Setting to `false`, returns the correct result for `B`.

**Comment by Alexhuszagh** [comment]
This occurs due to faulty logic on my part: it doesn't correctly check to see if it's an invalid digit, instead return `into_ok` and not `invalid_digit` which properly delegates out the subsequent steps.

```rust
            match iter.peek().map(|&c| char_to_digit_const(c, format.radix())) {
                // Valid digit, we have an invalid value.
                Some(Some(_)) => return into_error!(InvalidLeadingZeros, index),
                // Either not a digit that follows, or nothing follows.
                _ => return $into_ok!(<T>::ZERO, index),
            };
```

**Comment by Alexhuszagh** [comment]
Thanks for your contribution, I've just patched this in main. This will be in the next release.
